### ISSUE TITLE
colorbutton.py: PyQt5 not found in sys.modules

### ISSUE THREAD

**Issue by raquenaengineering** [learnpyqt/python-qtwidgets#3]
Hello,
I was trying to use this very good looking colorbutton widget included at the library, but when I've added it onto my code, crashed, asking for Pyside2.
So I've looked inside the code and figured out there's an if-else tense to choose between pyside and pyqt5.
I'm using Pyqt5, so the problem seems to be the "if 'PyQt5' in sys.modules:" isn't finding the Pyqt5 module.
If I just delete the if-else and force import pyqt5 everything works great!
Btw, the colorbuttons are very cool ;)

Cheers!

**Comment by mfitzp** [comment]
Hey @raquenaengineering thanks for the report. I *think* the issue is that you need to import PyQt5 before importing this module, eg. in your code do something like:

```
import PyQt5 # or other PyQt5 imports
from qtwidgets import ColorButton
```

...that should make sure it's in `sys.modules`. I'll check this again + update the docs to be clearer.
